<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Note adding</title>
</head>
<body>
<h3>Add your note:</h3>
<form method="post" action="/notebook">
    <input type="text" name="textarea" placeholder="Name">
    <input type="text" name="textarea" placeholder="Number">
    <input type="submit" name="button">
</form>
</body>
</html>